const products = [
  {
    id: 1,
    category: "House",
    name: "Modern Homes",
    price: 300,
    image: "/images/property-1.jpg",
  },
  {
    id: 11,
    category: "House",
    name: "Modern Homes",
    price: 300,
    image: "/images/pexels-binyamin-mellish-106399-removebg-preview.png",
  },
  {
    id: 12,
    category: "House",
    name: "Modern Homes",
    price: 300,
    image: "/images/pexels-expect-best-323780-removebg-preview.png",
  },
  {
    id: 13,
    category: "House",
    name: "Modern Homes",
    price: 300,
    image: "/images/pexels-graphicgumcom-1115804-removebg-preview.png",
  },
  {
    id: 2,
    category: "Apartment",
    name: "Comfortable Apartment",
    price: 6000,
    image: "/images/serenti33.jpg",
  },
  {
    id: 3,
    category: "Apartment",
    name: "Modern Apartment",
    price: 420,
    image: "/images/serenti31.jpg",
  },
  {
    id: 4,
    category: "House",
    name: "Modern Apartment",
    price: 300,
    image: "/images/serenti23.jpg",
  },
  {
    id: 5,
    category: "Apartment",
    name: "Comfortable Apartment",
    price: 6000,
    image: "/images/serenti33.jpg",
  },
  {
    id: 6,
    category: "House",
    name: "Comfortable Homes",
    price: 420,
    image: "/images/property-3.jpg",
  },
  {
    id: 7,
    category: "House",
    name: "Modern Homes",
    price: 300,
    image: "/images/blog-2.jpg",
  },
  {
    id: 8,
    category: "Apartment",
    name: "Comfortable Apartment",
    price: 6000,
    image: "/images/serenti28.jpg",
  },
  {
    id: 9,
    category: "Apartment",
    name: "Comfortable Apartment",
    price: 420,
    image: "/images/serenti30.jpg",
  },
  {
    id: 10,
    category: "Apartment",
    name: "Comfortable Apartment",
    price: 420,
    image: "/images/serenti33.jpg",
  },
  
];

export default products;
